set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR i686)

set(CMAKE_CROSSCOMPILING 1)

set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")

set(BINUTILS_PATH /usr/local/cross/bin)
set(TOOLCHAIN_PREFIX i686-elf-)

set(CMAKE_C_COMPILER ${BINUTILS_PATH}/${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_ASM_COMPILER ${BINUTILS_PATH}/${TOOLCHAIN_PREFIX}as)
set(CMAKE_CXX_COMPILER ${BINUTILS_PATH}/${TOOLCHAIN_PREFIX}g++)

set(CMAKE_FIND_ROOT_PATH /usr/local/cross/lib/gcc/i686-elf/12.2.0)

set(LINK_)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
